### ISSUE TITLE
Please add a read me and a license file

### ISSUE THREAD

**Issue by unixorn** [hgaiser/gruvbox-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add plugins with a readme so that users can tell what features they provide.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by hgaiser** [comment]
You're awfully quick, I only created this repository two days ago :p

But sure, I don't mind to add these.

**Comment by hgaiser** [comment]
Fixed with https://github.com/hgaiser/gruvbox-zsh/commit/7bbc530922bfa216422fdbbc13b3622f7bedf504 https://github.com/hgaiser/gruvbox-zsh/commit/1563b00744478e85f18bcb2445509cfe5d0f3052 .
