### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [hgaiser/gruvbox-zsh#2]
Sorry, I should have included this in https://github.com/hgaiser/gruvbox-zsh/issues/1 but can you please add a screen shot to the readme?

**Comment by hgaiser** [comment]
Yeah I wanted to do that yesterday but I didn't have the time for it. I'll
do that today probably.

**Comment by unixorn** [comment]
Thanks! I'll add it to the list after you close this.

**Comment by hgaiser** [comment]
Fixed with https://github.com/hgaiser/gruvbox-zsh/commit/d3c610f6db289aa1257ab8997831224837aeead6
