### ISSUE TITLE
[oh-my-zsh] plugin 'gruvbox' not found

### ISSUE THREAD

**Issue by 6upernova** [hgaiser/gruvbox-zsh#3]
Hi i keep getting this error and i dont know how to fix it, `[oh-my-zsh] plugin 'gruvbox' not found`
i have cloned the repository in `/home/noah/.oh-my-zsh/custom/plugins/gruvbox-zsh `,
this is my .zshrc file : 
```
# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git gruvbox)

source $ZSH/oh-my-zsh.sh 
```

**Comment by hgaiser** [comment]
I'm sorry, but this seems more like a configuration issue than an issue with this repo. I'm going to close this for now. If there's something to be done in this repo, feel free to reopen.

If I could help you I would, but I have practically zero experience with OMZ and how it is used.

**Comment by 6upernova** [comment]
oh  sorry, didint want to bother you, thx for the quick answer
